# Generated by Django 3.2.3 on 2021-05-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iu_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeduserobject',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
